#!/bin/bash
#
# Run all dotfiles installers.

set -e
cd "$DOTDIR"

# call these in a defined order
sh -c ./zsh/install.sh
sh -c ./git/install.sh
sh -c ./homebrew/install.sh
sh -c ./python3/install.sh
sh -c ./redshift/install.sh

# will prompt user asking if they want to reset mac defaults
${DOTDIR}/bin/set_mac_defaults
